name: Deploy Theme to Preproduction

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Obtener código del repositorio
        uses: actions/checkout@v3

      - name: 🚀 Subir archivos por SFTP Puro (FileZilla Mode)
        uses: wangyucode/sftp-upload-action@v2.0.2
        with:
          host: ${{ secrets.SFTP_SERVER }}
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          localDir: '.'
          remoteDir: '/home/dh_4wwubs/toolkitmarcachile.laq.cl/wp-content/themes/marcachile-toolkit-theme'
          exclude: '.git/**,.github/**'