name: Deploy Theme to Preproduction

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Obtener código del repositorio
        uses: actions/checkout@v3

      - name: 🚀 Subir archivos por SFTP Puro
        uses: wlixcc/SFTP-Deploy-Action@v3.3.3
        with:
          username: ${{ secrets.SFTP_USERNAME }}
          server: ${{ secrets.SFTP_SERVER }}
          password: ${{ secrets.SFTP_PASSWORD }}
          port: 22
          local_path: './'
          remote_path: '/home/dh_4wwubs/toolkitmarcachile.laq.cl/wp-content/themes/marcachile-toolkit-theme'
          args: '-o ConnectTimeout=5'